#########################################
# CONFIGURATION OF TOR CONTAINER
#########################################

#
# USE TOR BRIDGES
#
# To get Tor bridges head over to https://bridges.torproject.org and click on "Get bridges"
# Then you will see a form with "Advanced Options" header
# leave the Pluggable Transport as "obfs4" and click on the "Get Bridges" button
# Solve the captcha, you will get the bridge addresses (usually 3)
#
# Then, set TOR_USE_BRIDGES to "on" and initialize the TOR_BRIDGE_n_xxx options
# with information generated by the website for the 3 bridges.
#
# For instance, if the first line generated by the website is:
#   obfs4 24.106.248.94:65531 B9EFBC5... cert=yrX... iat-mode=0
# You will have to set:
#   TOR_BRIDGE_1_IP_PORT=24.106.248.94:65531
#   TOR_BRIDGE_1_ID=B9EFBC5...
#   TOR_BRIDGE_1_CERT=yrX...
#   TOR_BRIDGE_1_IAT_MODE=0
#


# Activate the use of Tor bridges
# Value: on | off
TOR_USE_BRIDGES=off

# Bridge 1
TOR_BRIDGE_1_IP_PORT=ToBeDefined
TOR_BRIDGE_1_ID=ToBeDefined
TOR_BRIDGE_1_CERT=ToBeDefined
TOR_BRIDGE_1_IAT_MODE=0

# Bridge 2
TOR_BRIDGE_2_IP_PORT=ToBeDefined
TOR_BRIDGE_2_ID=ToBeDefined
TOR_BRIDGE_2_CERT=ToBeDefined
TOR_BRIDGE_2_IAT_MODE=0

# Bridge 3
TOR_BRIDGE_3_IP_PORT=ToBeDefined
TOR_BRIDGE_3_ID=ToBeDefined
TOR_BRIDGE_3_CERT=ToBeDefined
TOR_BRIDGE_3_IAT_MODE=0
